version: '3.1'

services:

  adminer:
    build: .
    env_file:
      - docker-compose.env
    ports:
      - 7777:8080
    links:
      - mysql
    restart: "no"

  mysql:
    image: mysql:5.7
    env_file:
      - docker-compose.env
    environment:
      - MYSQL_ROOT_PASSWORD=P4$$w0rd
    restart: "no"

