version: '3.1'

services:

  adminer:
    build: .
    env_file: ['.services.env']
    ports: ['7777:8080']
    links: ['mysql']

  mysql:
    image: mysql:5.7
    env_file: ['.services.env']
    environment: ['MYSQL_ROOT_PASSWORD=P4$$w0rd']
